### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by samuel-rosa** [e-sensing/wtss.R#22]
Hi all, I am waiting for this package to be released soon. But I do hope you to simply call it wtss! Great work!

**Comment by edzer** [comment]
In that case, I'd recommend to rename the package (and GH repo) `wtss` - no need for the `.R`, which is usually indicating an R _script_.

**Comment by gqueiroz** [comment]
Hi Edzer,

Thank's for the explanation.
I will talk with Luiz Fernando to update the package name.
By the way, we have started a new version of WTSS server with less dependency of libraries:
https://github.com/eows/eows
It is in an early stage of development, but we are testing it here:
http://www.dpi.inpe.br/tws
Some examples of queries:
http://www.dpi.inpe.br/tws/wtss/list_coverages
http://www.dpi.inpe.br/tws/wtss/describe_coverage?name=mod13q1_512
http://www.dpi.inpe.br/tws/wtss/time_series?coverage=mod13q1_512&attributes=red,nir&latitude=-12&longitude=-54&start_date=2000-02-18&end_date=2001-01-01

Best Regards,
GRibeiro
